---
apiVersion: v1
kind: Service
metadata:
  name: cleo-backend-master
  labels:
    system: cleo
    service: cleo-backend
    environment: master
  namespace: default
spec:
  ports:
  - name: cleo
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    service: cleo-backend
    environment: master
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cleo-backend-master
  labels:
    system: cleo
    service: cleo-backend
    environment: master
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: cleo
        service: cleo-backend
        environment: master
    spec:
      containers:
      - name: aidbox
        image: "eu.gcr.io/vivid-kite-171620/cleo:v_f98a20f"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: secrets
        env:
        - name: PORT
          value: "8080"
        - name: PGHOST
          value: cleo-aidboxdb
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: postgres
        - name: PGDATABASE
          value: cleo
        - name: KAFKA_SERVER
          value: "kafka-kafka.default.svc.cluster.local:9092"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: openid-rsa
          mountPath: /var/openid-rsa
          readOnly: true
      volumes:
      - name: openid-rsa
        secret:
          secretName: openid-rsa
          items:
          - key: private
            path: id_rsa
          - key: public
            path: id_rsa.pub
